[package]
name = "tesmi/environmental-mini-games"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@^1.5"
Components = "sleitnick/component@2.4.6"
Signal = "sleitnick/signal@1.5.0"